"""HTML report generation with Jinja2 templates."""

from __future__ import annotations

from pathlib import Path

from pgxrx.core.variant import InterpretationReport

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>PGxRx Pharmacogenomics Report</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 40px; color: #222; }
h1 { border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
h2 { color: #2563eb; margin-top: 30px; }
table { border-collapse: collapse; width: 100%; margin: 15px 0; }
th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
th { background: #2563eb; color: white; }
tr:nth-child(even) { background: #f5f5f5; }
.phenotype { font-weight: bold; font-size: 1.1em; }
.poor { color: #dc2626; }
.intermediate { color: #d97706; }
.normal { color: #16a34a; }
.ultrarapid { color: #2563eb; }
.recommendation { background: #f0f7ff; border-left: 4px solid #2563eb; padding: 12px 16px; margin: 10px 0; }
.footer { margin-top: 40px; font-size: 0.85em; color: #666; border-top: 1px solid #ddd; padding-top: 15px; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.85em; color: white; }
.badge-A1 { background: #dc2626; }
.badge-A2 { background: #d97706; }
.badge-B { background: #2563eb; }
.badge-C { background: #6b7280; }
</style>
</head>
<body>
<h1>PGxRx Pharmacogenomics Report</h1>
<p><strong>Patient:</strong> {{ patient_name }}</p>
<p><strong>Generated:</strong> {{ timestamp }}</p>
<p><strong>Tool:</strong> PGxRx v0.1.0</p>
<p><strong>Disclaimer:</strong> This report is intended for clinical decision support only. All recommendations should be reviewed by a qualified healthcare professional. Not a substitute for clinical judgment.</p>

{% for report in reports %}
<h2>{{ report.gene }}</h2>

<table>
  <tr><th>Property</th><th>Value</th></tr>
  <tr><td>Sample ID</td><td>{{ report.sample_id }}</td></tr>
  <tr><td>Diplotype</td><td class="phenotype">{{ report.diplotype }}</td></tr>
  <tr><td>Activity Score</td><td>{{ report.activity_score }}</td></tr>
  <tr><td>Phenotype</td><td class="phenotype {{ report.phenotype_class }}">{{ report.phenotype }}</td></tr>
  <tr><td>Confidence</td><td>{{ report.confidence }}</td></tr>
</table>

{% if report.variants %}
<h3>Detected Variants</h3>
<table>
  <tr><th>Variant</th><th>rsID</th><th>Genotype</th></tr>
  {% for v in report.variants %}
  <tr><td>{{ v.allele_symbol }}</td><td>{{ v.rs_id or 'N/A' }}</td><td>{{ v.genotype or 'N/A' }}</td></tr>
  {% endfor %}
</table>
{% endif %}

{% if report.allele_calls %}
<h3>Allele Calls</h3>
<table>
  <tr><th>Allele</th><th>rsIDs</th><th>Activity Score</th><th>Description</th></tr>
  {% for ac in report.allele_calls %}
  <tr><td>{{ ac.allele_name }}</td><td>{{ ac.rs_ids | join(', ') }}</td><td>{{ ac.activity_score }}</td><td>{{ ac.description or 'N/A' }}</td></tr>
  {% endfor %}
</table>
{% endif %}

{% if report.dosing %}
<h3>Dosing Recommendations</h3>
{% for d in report.dosing %}
<div class="recommendation">
  <p><strong>Drug:</strong> {{ d.drug }} <span class="badge badge-{{ d.evidence_level }}">{{ d.evidence_level }}</span></p>
  <p>{{ d.recommendation }}</p>
</div>
{% endfor %}
{% endif %}

<hr>
{% endfor %}

<div class="footer">
  <p>Generated by PGxRx v0.1.0 | Guidelines: CPIC 2024 | Allele Nomenclature: PharmVar 2024.1</p>
  <p>Reference: Relling MV, et al. Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines.</p>
</div>
</body>
</html>
"""

_TEMPLATE_DIR = Path(__file__).parent / "templates"


def to_html(
    reports: list[InterpretationReport],
    patient_name: str = "Unknown",
    timestamp: str = "",
) -> str:
    """Generate HTML report from interpretation reports.

    Parameters
    ----------
    reports : list of InterpretationReport
    patient_name : patient identifier
    timestamp : override timestamp

    Returns
    -------
    str : HTML content
    """
    try:
        from jinja2 import Environment, FileSystemLoader
        env = Environment(loader=FileSystemLoader(str(_TEMPLATE_DIR)))
        template = env.get_template("report.html")
    except Exception:
        # Fall back to inline template
        from jinja2 import Template
        template = Template(_TEMPLATE)

    # Build template data
    template_reports = []
    for r in reports:
        phenotype = r.phenotype.phenotype if r.phenotype else "Unknown"
        phenotype_class = _phenotype_class(phenotype)
        template_reports.append({
            "sample_id": r.sample_id,
            "gene": r.gene,
            "diplotype": str(r.diplotype) if r.diplotype else "Unknown",
            "activity_score": r.diplotype.activity_score if r.diplotype else "N/A",
            "phenotype": phenotype,
            "phenotype_class": phenotype_class,
            "confidence": r.phenotype.confidence if r.phenotype else "N/A",
            "variants": [
                {
                    "allele_symbol": v.allele_symbol,
                    "rs_id": v.rs_id or "N/A",
                    "genotype": v.genotype or "N/A",
                }
                for v in r.variants
            ],
            "allele_calls": [
                {
                    "allele_name": ac.allele_name,
                    "rs_ids": ac.rs_ids,
                    "activity_score": ac.activity_score,
                    "description": _allele_desc(ac.gene, ac.allele_name),
                }
                for ac in r.allele_calls
            ],
            "dosing": [
                {
                    "drug": d.drug,
                    "recommendation": d.recommendation,
                    "evidence_level": d.evidence_level,
                }
                for d in r.dosing
            ],
        })

    ts = timestamp or reports[0].timestamp if reports else ""
    return template.render(
        patient_name=patient_name,
        timestamp=ts or "N/A",
        reports=template_reports,
    )


def _phenotype_class(phenotype: str) -> str:
    """Map phenotype to CSS class."""
    lower = phenotype.lower()
    if "poor" in lower or "non" in lower:
        return "poor"
    elif "intermediate" in lower or "reduced" in lower:
        return "intermediate"
    elif "normal" in lower or "extensive" in lower or "wild" in lower:
        return "normal"
    elif "ultrarapid" in lower or "rapid" in lower or "increased" in lower:
        return "ultrarapid"
    return "normal"


def _allele_desc(gene: str, allele: str) -> str:
    """Get allele description from bundled data."""
    from pgxrx.core.allele_mapper import _PHARMVAR_ALLELES
    info = _PHARMVAR_ALLELES.get(gene, {}).get(allele, {})
    return info.get("description", "")


def to_html_file(reports: list[InterpretationReport], path: str, patient_name: str = "Unknown"):
    """Write HTML report to file."""
    with open(path, "w") as f:
        f.write(to_html(reports, patient_name=patient_name))
